### ISSUE TITLE
[FE][Refactoring] 회원 파트 전체적인 리팩토링 작업

### ISSUE THREAD

**Issue by sagongjieun** [Cha-Young-Ho/TogetherSports#115]
# 제목
프론트 회원 부분 css, classname 등 통일 작업 필요

# 이슈에 대한 설명
본격적인 방 구현에 들어간 이 시점에서 구현된 회원 파트의 모든 css나 classname 통일성을 주고, 리팩토링을 한 번 진행해 봅시다!

**Comment by earthkingman** [comment]
마일스톤도 지정해주면 좋습니다!^^

**Comment by MoveRoad** [comment]
넵👍

**Comment by sagongjieun** [comment]
저는 완료했습니당 ✔
