### ISSUE TITLE
[Etc] 회원정보수정 페이지에 초기값이 잘 세팅돼있는지 테스트 필요

### ISSUE THREAD

**Issue by sagongjieun** [Cha-Young-Ho/TogetherSports#143]
# 제목
회원정보수정 페이지에 초기값이 잘 세팅돼있는지 테스트 필요

# 이슈에 대한 설명
회원정보수정 페이지에 초기값이 잘 세팅돼있는지 테스트 필요합니다.

**Comment by jeon-seun** [comment]
기대값: 회원정보수정 페이지 접근 시 수정폼에 현재 설정한 회원정보값이 올바르게 나타나야 함
