### ISSUE TITLE
[Feature Request] 백엔드 OAuth2 인증 기능 구현

### ISSUE THREAD

**Issue by jeon-seun** [Cha-Young-Ho/TogetherSports#151]
# Spring OAuth2 인증 구현
> 주요 작업 내용
* 프론트엔드 요청을 시작으로 하는 OAuth2 인증 과정을 구현한다.
* OAuth2 인증 성공 시 자체 서비스에 사용자 계정을 추가 해야한다. (이미 존재하는 경우 별도의 작업 X)
* OAuth2 인증 성공 이후 JWT Access Token 을 생성하고 발행해야 한다.

## OAuth2 인증 요청 처리
* 인증 요청 URL : /oauth2/authorization/{SNS}
* 해당 주소에 요청이 올 경우 화면을 백엔드에서 제공해서 인증과정 진행
*  인증 성공이후 프론트엔드의 /auth/saving 으로 리다이렉트
 
## OAuth2 로그인 회원 추가
* OAuth2 회원 인증이후 가져온 Email 정보로 기존회원인지 조회
* 기존 회원인 경우 별도의 추가작업 X
* 신규 회원인 경우 새 계정을 생성 

## OAuth2 로그인 이후 JWT 발행
* Email, DB Id, Nickname 정보를 클레임에 담아 쿼리 스트링에 포함한뒤 리다이렉트

**Comment by Cha-Young-Ho** [comment]
"OAuth2 회원 인증이후 가져온 Email 정보로 기존회원인지 조회" 부분에 추가 이슈가 있습니다.

# 추가 이슈
* OAuth2의 이메일이 겹칠 가능성이 존재합니다.

예시
> KAKAO : aabbcc@naver.com
> NAVER : aabbcc@naver.com

# 해결방안
## provider 값을 OAuth2 서비스에서 제공해줄 경우

1. 제공받은 provider를 추가적으로 확인해야합니다.
2. 같은 email이 존재해도 provider가 다르다면, 로그인 처리를 진행합니다.

## provider 값을 OAuth2 서비스에서 제공해주지 않는 경우
* redirect 과정 중간에 OAuth2 서비스 provider를 식별해야합니다.
* 프론트에게서 provider 를 제공받아야합니다.

**Comment by Cha-Young-Ho** [comment]
# 추가 이슈2
JWT Payload(Claim) 부분에 넣을 값을 정확히 산정해야 합니다.
현재 Email, DB Id, NickName이 포함되어 있습니다.

JWT Payload에 불필요한(사용되지 않을) 값이 존재하면 좋지 않은 점이 생깁니다.
* JWT 토큰의 길이 증가
* 복호화 과정 중 서버 부하 증가

약간의 값이 추가된다고 서버에 미미한 성능 지장이 오겠지만, 불필요한 성능 지장은 피하는 것이 좋을 것 같습니다.

**Comment by jeon-seun** [comment]
#155 이슈로 추가 이슈는 새로 정리해서 발행하였습니다.
