### ISSUE TITLE
[Feature Request] 다른 회원 정보 조회 기능 구현 필요

### ISSUE THREAD

**Issue by Cha-Young-Ho** [Cha-Young-Ho/TogetherSports#16]
# 제목
다른 회원 정보 조회 기능 구현

# 이슈에 대한 설명
다른 회원의 정보를 http로 주고받는 기능 구현 필요

브랜치는 다음과 같이 예상됨
* feature/backend/chayoungho/lookup-other-info

**Comment by MoveRoad** [comment]
확인했습니다.
