### ISSUE TITLE
[Etc] 이슈 명명 규칙 수정 필요

### ISSUE THREAD

**Issue by Cha-Young-Ho** [Cha-Young-Ho/TogetherSports#170]
# 제목
이슈 명명 규칙 수정 필요

# 이슈에 대한 설명
현재 이슈가 Position 별로 나누어져있지 않습니다.
Position을 추가하는 것이 좋을 것 같습니다.

## 명명 규칙 예시
* [BE][Feature Request] : BackEnd 이슈입니다.
* [FE][Feature Request] : FrontEnd 이슈입니다.
* [Both][Feature Request] : FrontEnd, BackEnd 이슈입니다.

**Comment by sagongjieun** [comment]
좋습니당 👍

**Comment by MoveRoad** [comment]
확인했습니다~

**Comment by jeon-seun** [comment]
good ~! 😊
