### ISSUE TITLE
[FE][Feature Request] Authorization 헤더값 수정

### ISSUE THREAD

**Issue by Cha-Young-Ho** [Cha-Young-Ho/TogetherSports#177]
# 제목
Access Token 헤더값 수정

# 이슈에 대한 설명
## 기존 값 
* "Authorization" : "Access Token"

## 수정 값
* "Authorization" : "Bearer AccessToken"

**Comment by MoveRoad** [comment]
확인했습니다.

**Comment by Cha-Young-Ho** [comment]
의견 수렴 완료
