### ISSUE TITLE
[Both][Refactoring] "추가 정보 입력" 및 "회원 정보 수정" 기능 병합

### ISSUE THREAD

**Issue by Cha-Young-Ho** [Cha-Young-Ho/TogetherSports#216]
# 제목
"추가 정보 입력" 기능과 "회원 정보 수정" 기능을 병합합니다.

# 이슈에 대한 설명
두 기능이 로직 상 다른 것이 없기 때문에 병합합니다.

## 제안
* api 명 : "회원 정보 입력"
* 기존의 추가 정보 입력을 호출 시, "회원 정보 입력"으로 호출합니다.
* 회원 정보 수정 시, 사용자가 입력하 값을 "회원 정보 입력"으로 호출합니다.
* 추 후에, "최초 입력"과 "회원 수정"이 나누어 질 수 있습니다. 회원 수정 시, 변경이 불가능한 값이 존재해질 경우 나누어야 합니다.

**Comment by MoveRoad** [comment]
확인했습니다.

**Comment by Cha-Young-Ho** [comment]
백엔드 구현완료
