### ISSUE TITLE
[Both][Refactoring] 닉네임 중복 확인 uri 수정

### ISSUE THREAD

**Issue by Cha-Young-Ho** [Cha-Young-Ho/TogetherSports#218]
# 제목
닉네임 중복 확인 uri 수정

# 이슈에 대한 설명
* 기존 api : 
    > /api/duplication
* 변경 후 api : 
    > /api/user/duplication/nickname

**Comment by sagongjieun** [comment]
프론트는 수정하였습니다 ✔

**Comment by Cha-Young-Ho** [comment]
백엔드 수정완료!
