### ISSUE TITLE
[Both][Refactoring] Navigation Bar 정보 요청 수정

### ISSUE THREAD

**Issue by Cha-Young-Ho** [Cha-Young-Ho/TogetherSports#219]
# 제목
Navigation Bar 정보 요청 수정

# 이슈에 대한 설명
## 기존 nav bar
* 기존의 navigation bar는 렌더링 시 마다, 정보 요청(프로필 이미지, 닉네임)을 합니다.

## 변경 후
* 리액트의 Redux 기능을 이용하여 유저 상태 정보를 저장합니다.
* 유저 상태 정보에 값이 없을 경우 서버에 JWT 토큰을 포함한 "내 정보 조회" api 를 호출하여 정보를 받습니다.

**Comment by MoveRoad** [comment]
FE는 수정 완료했습니다.

**Comment by Cha-Young-Ho** [comment]
완료
