### ISSUE TITLE
[Both][Etc] 방 설명(미참여) 페이지에 조회수에 대한 논의 필요

### ISSUE THREAD

**Issue by sagongjieun** [Cha-Young-Ho/TogetherSports#239]
# 제목
방 설명(미참여) 페이지에 조회수에 대한 논의 필요

# 이슈에 대한 설명
방 설명(미참여) 페이지에 조회수에 대한 논의가 필요합니다.

**Comment by Cha-Young-Ho** [comment]
방 설명 페이지 조회 시, 조회수가 +1 되는 형식은 어떤가요🥸

**Comment by sagongjieun** [comment]
좋습니다 👍
