### ISSUE TITLE
[Both][Refactoring] 방 조회 시, 요청자가 방장일 경우

### ISSUE THREAD

**Issue by Cha-Young-Ho** [Cha-Young-Ho/TogetherSports#243]
# 제목
방 조회 시, 요청자가 방장일 경우

# 이슈에 대한 설명
* 방 조회 시, 요청자가 방장일 경우 별도의 필드 값이 필요한지 정해야 합니다.

**Comment by MoveRoad** [comment]
+ 현재 방 입장 가능 인원에 대한 필터링 데이터가 명세에 없습니다. 놓친듯 싶어요. 수정 필요합니다

**Comment by Cha-Young-Ho** [comment]
확인 했습니다.

## 결정 사안
1. 방에 상세 정보 조회 시, 방장의 id를 응답한다.
2. Front 에서 방장의 id값을 통해 요청자가 방장인지 확인한다.
