### ISSUE TITLE
[Feature] 마이룸(my room) 기능 구현 필요

### ISSUE THREAD

**Issue by Cha-Young-Ho** [Cha-Young-Ho/TogetherSports#347]
# 마이룸

> 마이룸 기능 구현이 필요하다. 마이룸 기능에는 다음의 데이터가 응답된다.
* 내가 방장인 방
* 내가 참가한 방
* 다가오는 일정
* 
## 구현 배경

- 사용자가 자신의 일정 및 방을 보고싶을 때 "마이룸" 기능을 사용한다.

# 구현 방향

* URI : "/api/room/myroom"

## 주의 사항

1. JWT 인증이 필요한 기능이다. 요청에는 JWT Access Token이 포함되어야 한다.
2. 해당하는 방이 존재하지 않을 경우, 빈 리스트로 응답된다.

**Comment by Cha-Young-Ho** [comment]
# 1차 구현 완료

# To Do
1. 리팩토링
2. 코드 주석추가

**Comment by MoveRoad** [comment]
프론트 구현 완료했습니다.

**Comment by Cha-Young-Ho** [comment]
백엔드 api 구현 완료했습니다.

[api 명세서](https://candied-literature-ad0.notion.site/0acb8c5be09d46dc8cc6db98dd15d59c)
