### ISSUE TITLE
[Bug] 발견된 버그 사항

### ISSUE THREAD

**Issue by MoveRoad** [Cha-Young-Ho/TogetherSports#470]
# 버그 이름 (e.g 로그인 후 Navbar 에 프로필 갱신 버그)

- [x] 1. 채팅 호출 시 최신 20개가 아닌 첫 20개를 응답함
- [x] 2. 나가기 버튼이 아닌 그냥 페이지를 벗어날 때, 참여자 목록에서 해당 유저를 오프라인으로 표시하는 등으로 보여 줄 필요가 있음
- [x] 3. 타인 인기도를 올리면 내 입장에선 올라간게 보이지만 상대는 보이지않음(새로고침 시 반영됨)
- [x] 4. 방 삭제하기 버튼 지워야함
- [x] 5. 채팅 위로 올렸을때 20개씩 새로 요청
- [x] 6. 채팅만쳐도 방 수정 시간이 바뀜(backend)
- [x] 7. 그리고 현재시각 11시 37분인데 채팅치면 시간이 2시 ~~로나옴(backend?)
- [x] 8.  채팅 초반에 이미지가 안뜨는경우가있음(원인 미확인)
- [x] 9. 방에 잇다보면 알수없는 오류가 발생함(원인 미확인)
- [x] 10. 회원정보 없을 시 Attendance 요청 가지 않게 수정

**Comment by MoveRoad** [comment]
5, 8, 10번 수정했습니다.

**Comment by sagongjieun** [comment]
4번 수정했습니다.

**Comment by Cha-Young-Ho** [comment]
1. 요청이 다음과 같습니다.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/79268661/174584053-bfa56ff8-d50b-4b01-848d-c2b689c8a9ad.png">

쿼리 파라미터가 존재하지 않습니다. 확인한번 부탁드립니다.

[✅채팅내역 조회 노션 api 명세서](https://candied-literature-ad0.notion.site/530b9cb8a5174f4f949238bac03835f5)

**Comment by Cha-Young-Ho** [comment]
* 2번 :  이슈 새로 올렸습니다.

[✅ 이슈 페이지](https://github.com/Cha-Young-Ho/TogetherSports/issues/478)

**Comment by MoveRoad** [comment]
현재 9번 오류가 발생하지 않는걸로 확인되고 있어 이슈를 종료합니다.
