### ISSUE TITLE
[Refactoring] Room 관련 "수정시간(updatedTime)" 삭제가 필요합니다.

### ISSUE THREAD

**Issue by Cha-Young-Ho** [Cha-Young-Ho/TogetherSports#477]
# 리팩토링 내용
- Room 도메인 엔티티의 UpdatedTime 삭제가 필요합니다.

## 리팩토링 대상
- Room Auditing

## 리팩토링 내용
- Room Auditing 내용 중, updatedTime (엔티티 수정 시간)을 삭제해야 합니다.

### 현재 문제점

_**처음의 의도는**_ 방 엔티티에 대한 정보만 업데이트 되었을 때, 해당 방에 대한 "updatedTime"이 업데이트 되도록 하려는 목적이었습니다.
하지만 해당 엔티티와 매핑되어있는 타 테이블의 수정이 일어나도 해당 필드가 수정됩니다.

의도하지 않은 업데이트가 수행됩니다.

### 개선 내용
1. 해당 필드의 삭제가 필요합니다.
2. jpa auditing 기능에는 특별 테이블이나 특별 컬럼에 대한 update 제외 기능이 없습니다. 해당 기능을 이용하려면 따로 row Query를 통해서 DB에 DML을 직접 날려야 합니다.
3. 2번의 방법을 채택할 경우에 대부분의 로직에 row Query를 이용해야하는 단점이 있습니다.

**Comment by sagongjieun** [comment]
확인했습니다! 프론트도 해당 부분 삭제해둘게요

**Comment by sagongjieun** [comment]
프론트 완료했습니당
