### ISSUE TITLE
[Bug] 발견된 버그 사항 #2

### ISSUE THREAD

**Issue by Cha-Young-Ho** [Cha-Young-Ho/TogetherSports#509]
# 로컬 테스트 후 발견된 버그사항

## 버그 대상

- 프론트
- 백

## Bug List

- [x] 1. 추가 입력 시, 중복 확인 후 다른 닉네임으로 변경하면 넘어감
- [x] 2. 닉네임이 중복된 상태로 추가 입력 시, "중복된 닉네임이 있습니다"라고 알림창이 뜸("중복된 닉네임입니다."로 건의)
- [x] 3. 추가 입력 시, "이전" 버튼을 누를 경우 이전에 입력한 값들이 사라짐
- [x] 4. 로그아웃 HTTP Method 수정 필요(현재 POST -> 수정 DELETE)
- [x] 5. 방 정보 수정 시, 인원과 수정 그리고 제목까지 모두 변경을 해야 수정 요청이 날아감
- [x] 6. 방 정보 수정 완료 시, 다음과 같은 에러가 뜸
> 
<img width="1044" alt="스크린샷 2022-07-04 오후 8 59 54" src="https://user-images.githubusercontent.com/79268661/177153815-95f76814-8668-4129-93ed-7c2346437eba.png">

- [x] 7. 방 정보 수정 시, "제목을 입력해주세요"라는 알림창이 뜬 후 다음과 같은 에러가 뜸
> 
<img width="1040" alt="스크린샷 2022-07-04 오후 8 58 00" src="https://user-images.githubusercontent.com/79268661/177153928-43b07669-3853-4b64-8c4d-a80001ffbfec.png">

- [x]  8. 방 소켓 연결 시, detail이 먼저 호출되는 경우가 있어서 자기 자신은 "OFFLINE"으로 표기 됨(서버에서 OFFLINE을 받을 수 밖에 없음)
- [x]  9. excercise 필드 값 수정 고려해야함(ex. 축구 -> soccer)

**Comment by MoveRoad** [comment]
수정 완료했습니다.

**Comment by MoveRoad** [comment]
4-8번 수정 했습니다. 9번은 무슨 내용인가요?

**Comment by Cha-Young-Ho** [comment]
9번은 필드값을 한국어에서 영어로 바꾸는걸 말하는겁니다!

**Comment by sagongjieun** [comment]
9번 완료하였습니다.
